// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Roski.Api.Persistence;

#nullable disable

namespace Roski.Api.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509132313_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Roski.Api.Persistence.Lift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<GeoLineString>("Geometry")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Hours")
                        .HasColumnType("text");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("LiftType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("OsmId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ResortId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OsmId");

                    b.HasIndex("ResortId");

                    b.ToTable("lifts", (string)null);
                });

            modelBuilder.Entity("Roski.Api.Persistence.Resort", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CenterLat")
                        .HasColumnType("double precision");

                    b.Property<double>("CenterLon")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("ElevationMax")
                        .HasColumnType("integer");

                    b.Property<int?>("ElevationMin")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TerrainModelUrl")
                        .HasColumnType("text");

                    b.Property<double>("TerrainOriginLat")
                        .HasColumnType("double precision");

                    b.Property<double>("TerrainOriginLon")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<WebcamLink>>("Webcams")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("resorts", (string)null);
                });

            modelBuilder.Entity("Roski.Api.Persistence.Slope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<GeoLineString>("Geometry")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<int?>("LengthM")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("OsmId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ResortId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OsmId");

                    b.HasIndex("ResortId");

                    b.ToTable("slopes", (string)null);
                });

            modelBuilder.Entity("Roski.Api.Persistence.Lift", b =>
                {
                    b.HasOne("Roski.Api.Persistence.Resort", null)
                        .WithMany("Lifts")
                        .HasForeignKey("ResortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Roski.Api.Persistence.Slope", b =>
                {
                    b.HasOne("Roski.Api.Persistence.Resort", null)
                        .WithMany("Slopes")
                        .HasForeignKey("ResortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Roski.Api.Persistence.Resort", b =>
                {
                    b.Navigation("Lifts");

                    b.Navigation("Slopes");
                });
#pragma warning restore 612, 618
        }
    }
}
